# The shader disk cache's source version (shaderDiskCache.h): a hash over every file the shader
# recompiler is built from, so that a build whose recompiler differs in any way never uses entries
# an older one wrote. Run at build time (cmake -P) whenever one of the files may have changed.
#
# SOURCE_DIR  the src directory (include root)
# SEEDS_FILE  a file listing, one per line, the files the recompiler is built from (its sources,
#             the shader stage helpers, the format tables, the cache's own encoding)
# ROOTS       |-separated directories whose headers the build lists as dependencies of this step;
#             an included header outside them fails the build (add its directory to ROOTS)
# EXTRA       text hashed with the files (compiler, build type)
# OUTPUT      the generated header
# STAMP       touched at every run
#
# The project headers the seeds include are followed transitively and hashed too. The KYTY_*
# environment switches named in the shader sources are listed, so the session key can record
# their values.
cmake_minimum_required(VERSION 3.20)

file(STRINGS "${SEEDS_FILE}" SEEDS)
set(pending ${SEEDS})
set(visited)
while(pending)
	list(POP_FRONT pending current)
	get_filename_component(current "${current}" ABSOLUTE)
	if(current IN_LIST visited)
		continue()
	endif()
	if(NOT EXISTS "${current}")
		message(FATAL_ERROR "Shader cache version: ${current} does not exist")
	endif()
	list(APPEND visited "${current}")
	get_filename_component(directory "${current}" DIRECTORY)
	file(STRINGS "${current}" includes REGEX "^[ \t]*#[ \t]*include[ \t]*\"[^\"]+\"")
	foreach(line IN LISTS includes)
		string(REGEX REPLACE "^[ \t]*#[ \t]*include[ \t]*\"([^\"]+)\".*$" "\\1" included "${line}")
		foreach(base IN ITEMS "${directory}" "${SOURCE_DIR}")
			if(EXISTS "${base}/${included}" AND NOT IS_DIRECTORY "${base}/${included}")
				get_filename_component(resolved "${base}/${included}" ABSOLUTE)
				if(NOT resolved IN_LIST visited)
					list(APPEND pending "${resolved}")
				endif()
				break()
			endif()
		endforeach()
	endforeach()
endwhile()

get_filename_component(source_root "${SOURCE_DIR}" ABSOLUTE)
string(REPLACE "|" ";" ROOTS "${ROOTS}")
set(absolute_roots)
foreach(root IN LISTS ROOTS)
	get_filename_component(root "${root}" ABSOLUTE)
	list(APPEND absolute_roots "${root}")
endforeach()
set(absolute_seeds)
foreach(seed IN LISTS SEEDS)
	get_filename_component(seed "${seed}" ABSOLUTE)
	list(APPEND absolute_seeds "${seed}")
endforeach()

list(SORT visited)
set(manifest "${EXTRA}\n")
set(switches)
foreach(current IN LISTS visited)
	if(NOT current IN_LIST absolute_seeds)
		set(covered FALSE)
		foreach(root IN LISTS absolute_roots)
			string(FIND "${current}" "${root}/" position)
			if(position EQUAL 0)
				set(covered TRUE)
				break()
			endif()
		endforeach()
		if(NOT covered)
			message(FATAL_ERROR "Shader cache version: the recompiler includes ${current}, which is "
			                    "not under the directories the build watches for it: add its "
			                    "directory to the shader cache ROOTS in CMakeLists.txt")
		endif()
	endif()
	file(SHA256 "${current}" digest)
	file(RELATIVE_PATH relative "${source_root}" "${current}")
	string(APPEND manifest "${relative} ${digest}\n")
	string(FIND "${current}" "${source_root}/graphics/shader/" in_shader)
	if(in_shader EQUAL 0)
		file(STRINGS "${current}" lines REGEX "\"KYTY_[A-Z0-9_]+\"")
		foreach(line IN LISTS lines)
			string(REGEX MATCHALL "\"KYTY_[A-Z0-9_]+\"" names "${line}")
			list(APPEND switches ${names})
		endforeach()
	endif()
endforeach()

string(SHA256 version "${manifest}")
string(SUBSTRING "${version}" 0 16 version)
list(REMOVE_DUPLICATES switches)
list(SORT switches)
list(APPEND switches "\"\"")
list(JOIN switches ",\n\t    " switch_list)
list(LENGTH visited file_count)

set(content "// Generated by src/shader_cache_version.cmake from ${file_count} files: do not edit.
#ifndef KYTY_GENERATED_SHADERCACHEVERSION_H_
#define KYTY_GENERATED_SHADERCACHEVERSION_H_

#include <cstdint>
#include <string_view>

namespace Libs::Graphics::ShaderDiskCacheVersion {

inline constexpr uint64_t SourceVersion = 0x${version}ull;

// The environment switches the shader sources name; the empty entry ends the list.
inline constexpr std::string_view RecompilerSwitches[] = {
	    ${switch_list}
};

} // namespace Libs::Graphics::ShaderDiskCacheVersion

#endif
")

# The header is rewritten only when it changes (nothing recompiles otherwise); the stamp tells the
# build this step ran.
set(previous)
if(EXISTS "${OUTPUT}")
	file(READ "${OUTPUT}" previous)
endif()
if(NOT previous STREQUAL content)
	file(WRITE "${OUTPUT}" "${content}")
endif()
file(TOUCH "${STAMP}")
